### ISSUE TITLE
Error when not using branch shows incorrect pscale command

### ISSUE THREAD

**Issue by jnunemaker** [planetscale/planetscale_rails#19]
I tried to migrate without making a branch to test something else and got this error:

<img width="576" alt="migrate switch branch help error" src="https://github.com/planetscale/planetscale_rails/assets/235/50ea70f3-b83f-4a0e-afd6-84b4d98f7bb2">

But the command to switch branches is:

```
pscale branch switch my-new-branch-name --database my-db-name --create --wait
```

Should be an easy fix but I didn't have time to look into it.

**Comment by mscoutermarsh** [comment]
Thank you! We'll fix
